### ISSUE TITLE
feat: Usable out of the box metrics

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/go-libp2p-resource-manager#50]
resource manager should expose metrics around the current resource usage. And aggregating where necessary.

It doesn't make sense to record every peer's resource usage, but aggregates would still be very valuable (avg, p90, p99, max, min) to operators. 

In most use cases the end-user will want this information, and we already record this so we should expose.

**Comment by marten-seemann** [comment]
Should this be part of https://github.com/libp2p/go-libp2p/issues/1356? Unfortunately, the API we were going to use is still in Alpha.

**Comment by MarcoPolo** [comment]
It could be, but this is tightly scoped and I don't think it should be blocked on 1356 or on waiting for opentelemetry metrics to come out of alpha.

**Comment by BigLep** [comment]
I know there is work underway on this.  I'm putting in my notes for the high-level dashboard I think would be useful for an operator to see:
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/85411/174457375-dfc8450a-52ae-45f0-988c-31cb3ce73160.png">
(mocked from [here](https://docs.google.com/spreadsheets/d/1zPr7BL2zXcE11ucox1v2s6DPA0RXM9CgONEpYrWGcTY/edit#gid=0))

The system/transient graphs straight copy/pastes from [the observable](https://observablehq.com/d/ea5897ee047a987e).  The other scops are showing an aggregation.  At the minimum when it comes to aggregation I would want to see:
* n - the number of values that were aggregated.  It should be graphed on a separate axis (left axis).  For example, with peer scope, at the time of metric datapoint generation, it would denote how many peers were in that metric interval.
* p50 - at the time of datapoint generation, would show the median value.  It should be on a separate axis (right axis)
* p90 - show the 90th percentil
* p100 - show the max value

We could obviously have other percentiles too.  
If percentiles are too expensive to calculate because of the sorting required we could get away with average and max for now.

**Comment by BigLep** [comment]
Once this feature is developed, we also need to make sure user's can discover it easily enough. There is a docs issue to give visibility to it here: https://github.com/libp2p/docs/issues/158
